name: pay_in
description: Aplikasi mobile untuk freelancer dalam membuat invoice profesional
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  get: ^4.6.6
  
  # Local Storage (Hapus Hive, gunakan SharedPreferences saja)
  shared_preferences: ^2.2.3
  
  # PDF Generation & File Handling
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.3
  open_file: ^3.3.2
  
  # Date & Time
  intl: ^0.20.2
  
  # Email & Sharing
  share_plus: ^7.2.2
  mailer: ^6.0.1
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  
  # Form & Validation
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  
  # Charts & Analytics
  fl_chart: ^0.68.0
  
  # Utilities
  uuid: ^4.4.0
  currency_formatter: ^2.2.0

  # Email service sesuai search results
  emailjs: ^4.0.0

  # Update google_fonts sesuai search results untuk mengatasi konflik versi
  google_fonts: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
